<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.6.1" />
    <PackageVersion Include="Duende.IdentityServer" Version="8.1.0-preview.4" />
    <PackageVersion Include="Duende.IdentityServer.EntityFramework" Version="8.0.9" />
    <PackageVersion Include="Duende.Storage.PostgreSql" Version="2.0.0-preview.3" />
    <PackageVersion Include="Duende.UserManagement.IdentityServer8" Version="2.0.0-preview.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
  </ItemGroup>
</Project>