<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Zaiware.Platform.IdentityServer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityServer" />
  </ItemGroup>
</Project>
